name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - v1.2.1

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: apt install
        run: |
          sudo apt update -y
          sudo apt install -y $(cat pkglist.txt)

      - name: set LANG
        run: sh lang-zh.sh

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Git Config
        run: git config user.name whitewum && git config user.email min.wu@vesoft.com

      - name: mike list
        run: |
          mike list
          #mike delete 1.2 -p

      - name: Mike Deploy 1.2.1
        run: |
          mike deploy 1.2.1 -p --rebase
          mike list  

      - name: show git branch
        run: | 
          git branch
          git checkout gh-pages

      - name: Compress
        run: |
           tar -vczf nebula-docs.tar.gz 1.2.1 versions.json index.html
           
      - name: Transfer
        # uses: garygrossgarten/github-action-scp@release
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER_NAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.port }}
            source: nebula-docs.tar.gz
            target: /usr/web

      - name: UnCompress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /usr/web/nebula-docs/
            tar -xzf /usr/web/nebula-docs.tar.gz -C /usr/web/nebula-docs/
            #pip3 install --upgrade pip
            #pip3 install -r /usr/web/nebula-docs/requirements.txt
            #sudo apt install -y $(cat /usr/web/nebula-docs/pkglist.txt)
            #sh /usr/web/nebula-docs/lang-zh.sh
      #     github_token: ${{ secrets.DEPLOY_TOKEN }}
      #     publish_dir: ./site
